# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "À propos"
  pageRef = "pages/_Apropos"
  weight = 1

[[main]]
  name = "Projet"
  parent = "À propos"
  pageRef = "pages/_Apropos/1_Projet"
  weight = 11

[[main]]
  name = "Axes"
  parent = "À propos"
  pageRef = "pages/_Apropos/2_Axes"
  weight = 12

[[main]]
  name = "Partenaires"
  parent = "À propos"
  pageRef = "pages/_Apropos/3_Partenaires"
  weight = 13

[[main]]
  name = "MSHB"
  url = "https://www.mshb.fr/"
  weight = 131


[[main]]
  name = "Événements"
  pageRef = "pages/_Evenements"
  weight = 2

[[main]]
  name = "Formations"
  parent = "Événements"
  pageRef = "categories/formations"
  weight = 21

[[main]]
  name = "Séminaires"
  parent = "Événements"
  pageRef = "categories/séminaires"
  weight = 22

[[main]]
  name = "Colloques et JE"
  parent = "Événements"
  pageRef = "categories/colloques-et-JE"
  weight = 23

[[main]]
  name = "Documentation"
  pageRef = "pages/_Documentation"
  weight = 3

[[main]]
  name = "Écosystème"
  parent = "Documentation"
  pageRef = "categories/écosystème"
  weight = 31

[[main]]
  name = "Démarches"
  parent = "Documentation"
  pageRef = "categories/démarches"
  weight = 32

[[main]]
  name = "Outils"
  parent = "Documentation"
  pageRef = "categories/outils"
  weight = 33

[[subnavigation]]
  name = "Éthique et juridique"
  pageRef = "tags/ethique-et-juridique"
  weight = 10

[[subnavigation]]
  name = "Administratif"
  pre = "github"
  pageRef = "tags/administratif"
  weight = 10


#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
